// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package mn_back

import (
	"github.com/IntegralTeam/energi/common"
)

// MarshalTOML marshals as TOML.
func (c Config) MarshalTOML() (interface{}, error) {
	type Config struct {
		Enabled    bool
		Passphrase string
		CraAddress common.Address
	}
	var enc Config
	enc.Enabled = c.Enabled
	enc.Passphrase = c.Passphrase
	enc.CraAddress = c.CraAddress
	return &enc, nil
}

// UnmarshalTOML unmarshals from TOML.
func (c *Config) UnmarshalTOML(unmarshal func(interface{}) error) error {
	type Config struct {
		Enabled    *bool
		Passphrase *string
		CraAddress *common.Address
	}
	var dec Config
	if err := unmarshal(&dec); err != nil {
		return err
	}
	if dec.Enabled != nil {
		c.Enabled = *dec.Enabled
	}
	if dec.Passphrase != nil {
		c.Passphrase = *dec.Passphrase
	}
	if dec.CraAddress != nil {
		c.CraAddress = *dec.CraAddress
	}
	return nil
}
